### ISSUE TITLE
Payment result notification verification

### ISSUE THREAD

**Issue by honggang007** [flitto/wechatpay#11]
WeChatPay.prototype.validate = function (xml, callback) {
    const  _this = this;
    return util.parseXML(xml, function (err, json) {

        let error = null,
            data;
        if (err) {
            error = new Error();
            err.name = 'XMLParseError';
            return callback(err, xml);
        }
        data = json ? json : {};
        if (data.return_code === 'FAIL') {
            error = new Error(data.return_msg);
            error.name = 'ProtocolError';
        } else if(_this.cfg.appid !== data.appid) {
            error = new Error();
            error.name = 'InvalidAppId';
        } else if (_this.cfg.mch_id && _this.cfg.mch_id !== data.sub_mch_id) {
            error = new Error();
            error.name = 'InvalidSubMchId';
        } else if (_this.getSign(data) !== data.sign) {
            error = new Error();
            error.name = 'InvalidSignature';
        }
        return callback(error, data);
    });
};

**Comment by honggang007** [comment]
WeChatPay.prototype.validate = function (xml, callback) {
const _this = this;
return util.parseXML(xml, function (err, json) {

    let error = null,
        data;
    if (err) {
        error = new Error();
        err.name = 'XMLParseError';
        return callback(err, xml);
    }
    data = json ? json : {};
    if (data.return_code === 'FAIL') {
        error = new Error(data.return_msg);
        error.name = 'ProtocolError';
    } else if(_this.cfg.appid !== data.appid) {
        error = new Error();
        error.name = 'InvalidAppId';
    } else if (_this.cfg.mch_id && _this.cfg.mch_id !== data.mch_id) {
        error = new Error();
        error.name = 'InvalidSubMchId';
    } else if (_this.getSign(data) !== data.sign) {
        error = new Error();
        error.name = 'InvalidSignature';
    }
    return callback(error, data);
});
};

**Comment by dankang** [comment]
Thank you for your suggestion, but we think that the validation function is better to be written by the developer because every error handling function is different every case.
